# Generated by Django 5.2.5 on 2025-08-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('title', models.CharField(help_text='会议标题', max_length=200, verbose_name='会议标题')),
                ('description', models.TextField(blank=True, help_text='会议描述', null=True, verbose_name='会议描述')),
                ('location', models.CharField(blank=True, help_text='会议地点', max_length=200, null=True, verbose_name='会议地点')),
                ('start_time', models.DateTimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('keywords', models.TextField(blank=True, help_text='会议关键词/专有名词，逗号分隔，将应用到所有关联录音处理', null=True, verbose_name='关键词')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已取消')], default=0, help_text='会议状态', verbose_name='会议状态')),
            ],
            options={
                'verbose_name': '会议信息',
                'verbose_name_plural': '会议信息',
                'db_table': 'meet_meeting',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('content', models.TextField(help_text='纲要内容', verbose_name='纲要内容')),
                ('generate_status', models.IntegerField(choices=[(0, '未生成'), (1, '生成中'), (2, '已生成'), (3, '生成失败')], default=0, help_text='生成状态', verbose_name='生成状态')),
            ],
            options={
                'verbose_name': '会议纲要',
                'verbose_name_plural': '会议纲要',
                'db_table': 'meet_summary',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('upload_location', models.CharField(blank=True, help_text='上传地点', max_length=200, null=True, verbose_name='上传地点')),
                ('duration', models.IntegerField(blank=True, help_text='录音时长（秒）', null=True, verbose_name='录音时长')),
                ('keywords', models.TextField(blank=True, help_text='录音特有关键词，逗号分隔，会与会议关键词合并使用', null=True, verbose_name='录音关键词')),
                ('process_status', models.IntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已完成'), (3, '处理失败')], default=0, help_text='处理状态', verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '录音文件',
                'verbose_name_plural': '录音文件',
                'db_table': 'meet_recording',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('speaker_id', models.CharField(help_text='AI识别的说话人标识（如：说话人1、说话人2）', max_length=50, verbose_name='说话人标识')),
                ('name', models.CharField(blank=True, help_text='说话人姓名', max_length=100, null=True, verbose_name='姓名')),
                ('title', models.CharField(blank=True, help_text='说话人职务', max_length=100, null=True, verbose_name='职务')),
                ('department', models.CharField(blank=True, help_text='说话人部门', max_length=100, null=True, verbose_name='部门')),
                ('company', models.CharField(blank=True, help_text='说话人公司', max_length=200, null=True, verbose_name='公司')),
            ],
            options={
                'verbose_name': '说话人',
                'verbose_name_plural': '说话人',
                'db_table': 'meet_speaker',
                'ordering': ['recording', 'speaker_id'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('start_time', models.IntegerField(help_text='开始时间（毫秒）', verbose_name='开始时间')),
                ('end_time', models.IntegerField(help_text='结束时间（毫秒）', verbose_name='结束时间')),
                ('text', models.TextField(help_text='转录文本', verbose_name='转录文本')),
                ('confidence', models.FloatField(blank=True, help_text='转录置信度（0-1）', null=True, verbose_name='置信度')),
            ],
            options={
                'verbose_name': '转录文本片段',
                'verbose_name_plural': '转录文本片段',
                'db_table': 'meet_transcript_segment',
                'ordering': ['recording', 'start_time'],
            },
        ),
    ]
