# Generated by Django 5.2.5 on 2025-08-19 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meet', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='meetingsummary',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='meetingsummary',
            name='meeting',
            field=models.OneToOneField(help_text='关联会议', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meet.meeting', verbose_name='关联会议'),
        ),
        migrations.AddField(
            model_name='recording',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='recording',
            name='file',
            field=models.ForeignKey(help_text='录音文件', on_delete=django.db.models.deletion.CASCADE, to='system.file', verbose_name='录音文件'),
        ),
        migrations.AddField(
            model_name='recording',
            name='meeting',
            field=models.ForeignKey(help_text='关联会议', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meet.meeting', verbose_name='关联会议'),
        ),
        migrations.AddField(
            model_name='recording',
            name='uploader',
            field=models.ForeignKey(help_text='上传人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_uploader', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='recording',
            field=models.ForeignKey(help_text='关联录音', on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='meet.recording', verbose_name='关联录音'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='recording',
            field=models.ForeignKey(help_text='关联录音', on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meet.recording', verbose_name='关联录音'),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='speaker',
            field=models.ForeignKey(help_text='说话人', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meet.speaker', verbose_name='说话人'),
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together={('recording', 'speaker_id')},
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['recording', 'start_time'], name='meet_transc_recordi_8cd731_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['speaker', 'start_time'], name='meet_transc_speaker_e4f90d_idx'),
        ),
    ]
