# Generated by Django 5.2.5 on 2025-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='full_text',
            field=models.TextField(blank=True, help_text='完整转录文本', null=True, verbose_name='完整转录文本'),
        ),
        migrations.AlterField(
            model_name='transcriptsegment',
            name='end_time',
            field=models.TimeField(help_text='结束时间（格式如00:05:53.120）', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='transcriptsegment',
            name='start_time',
            field=models.TimeField(help_text='开始时间（格式如00:05:53.120）', verbose_name='开始时间'),
        ),
    ]
