# Generated by Django 5.2.5 on 2025-09-02 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_recording_full_text_alter_transcriptsegment_end_time_and_more'),
        ('system', '0004_alter_role_column_alter_role_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(help_text='会议所属人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_meetings', to=settings.AUTH_USER_MODEL, verbose_name='所属人'),
        ),
        migrations.CreateModel(
            name='MeetingPhoto',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('photo_type', models.IntegerField(choices=[(1, '会议照片'), (2, '签到表')], verbose_name='照片类型')),
                ('description', models.CharField(blank=True, help_text='照片描述', max_length=200, null=True, verbose_name='描述')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.file', verbose_name='图片文件')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meet.meeting', verbose_name='关联会议')),
            ],
            options={
                'verbose_name': '会议照片',
                'verbose_name_plural': '会议照片',
                'db_table': 'meet_photo',
                'ordering': ['photo_type', '-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('name', models.CharField(help_text='人员姓名', max_length=100, verbose_name='姓名')),
                ('company', models.CharField(blank=True, help_text='所属单位', max_length=200, null=True, verbose_name='单位')),
                ('title', models.CharField(blank=True, help_text='职务', max_length=100, null=True, verbose_name='职务')),
                ('is_moderator', models.BooleanField(default=False, help_text='是否为会议主持人', verbose_name='是否主持人')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meet.meeting', verbose_name='关联会议')),
                ('user', models.ForeignKey(blank=True, help_text='如果是系统用户则关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participations', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '参会人员',
                'verbose_name_plural': '参会人员',
                'db_table': 'meet_participant',
                'ordering': ['-is_moderator', 'name'],
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MeetingShare',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('is_active', models.BooleanField(default=True, help_text='是否有效分享', verbose_name='是否有效')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('meeting', models.ForeignKey(help_text='关联会议', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='meet.meeting', verbose_name='关联会议')),
                ('shared_user', models.ForeignKey(help_text='被分享用户', on_delete=django.db.models.deletion.CASCADE, related_name='shared_meetings', to=settings.AUTH_USER_MODEL, verbose_name='被分享用户')),
            ],
            options={
                'verbose_name': '会议分享',
                'verbose_name_plural': '会议分享',
                'db_table': 'meet_meeting_share',
                'ordering': ['-create_datetime'],
                'unique_together': {('meeting', 'shared_user')},
            },
        ),
    ]
