# Generated by Django 5.2.5 on 2025-09-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_meeting_owner_meetingphoto_meetingparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name',
            field=models.CharField(blank=True, help_text='录音名称，默认为文件名', max_length=200, null=True, verbose_name='录音名称'),
        ),
    ]
