# Generated by Django 5.2.5 on 2025-09-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_recording_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['recording', 'speaker_sequence'], 'verbose_name': '说话人', 'verbose_name_plural': '说话人'},
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker_id',
            new_name='speaker_sequence',
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together={('recording', 'speaker_sequence')},
        ),
    ]
