# Generated by Django 5.2.5 on 2025-09-16 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_alter_speaker_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranscriptSegment',
            new_name='Segment',
        ),
    ]
