# Generated by Django 5.2.5 on 2025-09-16 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_rename_transcriptsegment_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.AddField(
            model_name='meeting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='会议地点名称'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='经度'),
        ),
    ]
