# Generated by Django 5.2.5 on 2025-09-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_remove_meeting_location_meeting_latitude_and_more'),
        ('system', '0007_alter_file_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsummary',
            name='report_file',
            field=models.ForeignKey(blank=True, help_text='会议报告文件', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.file', verbose_name='会议报告文件'),
        ),
        migrations.AlterField(
            model_name='meetingsummary',
            name='generate_status',
            field=models.IntegerField(choices=[(0, '未生成'), (1, '生成中'), (2, '已生成'), (3, '生成失败')], default=0, help_text='会议报告生成状态', verbose_name='会议报告生成状态'),
        ),
    ]
