# Generated by Django 5.2.5 on 2025-09-18 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_meetingsummary_report_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'name', 'company'), ('meeting', 'user')},
        ),
    ]
