# Generated by Django 5.2.5 on 2025-09-23 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_alter_meetingparticipant_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddField(
            model_name='meeting',
            name='delete_status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '软删除'), (2, '硬删除')], default=0, help_text='删除状态标识', verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='deleted_datetime',
            field=models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='deleted_reason',
            field=models.CharField(blank=True, help_text='删除原因', max_length=255, null=True, verbose_name='删除原因'),
        ),
    ]
