# Generated by Django 5.2.5 on 2025-11-04 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_alter_meetingparticipant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '已取消')], default=0, help_text='会议状态', verbose_name='会议状态'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'name', 'company'), ('meeting', 'user')},
        ),
        migrations.CreateModel(
            name='RealtimeRecordingSession',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('belong_dept', models.IntegerField(blank=True, help_text='数据归属部门', null=True, verbose_name='数据归属部门')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('session_id', models.CharField(help_text='实时录音会话唯一标识', max_length=100, unique=True, verbose_name='会话ID')),
                ('recording_status', models.IntegerField(choices=[(0, '未开始'), (1, '录音中'), (2, '已暂停'), (3, '已停止'), (4, '处理中'), (5, '已完成'), (6, '已失败')], default=0, help_text='实时录音状态', verbose_name='录音状态')),
                ('temp_audio_path', models.CharField(blank=True, help_text='WebM格式的临时录音文件路径', max_length=500, null=True, verbose_name='临时音频文件路径')),
                ('pause_count', models.IntegerField(default=0, help_text='用户暂停录音的次数', verbose_name='暂停次数')),
                ('last_pause_time', models.DateTimeField(blank=True, help_text='最后一次暂停的时间', null=True, verbose_name='最后暂停时间')),
                ('last_resume_time', models.DateTimeField(blank=True, help_text='最后一次恢复录音的时间', null=True, verbose_name='最后恢复时间')),
                ('started_at', models.DateTimeField(blank=True, help_text='第一次开始录音的时间', null=True, verbose_name='开始录音时间')),
                ('stopped_at', models.DateTimeField(blank=True, help_text='最终停止录音的时间', null=True, verbose_name='停止录音时间')),
                ('task_id', models.CharField(blank=True, help_text='Celery任务ID', max_length=100, null=True, verbose_name='后台任务ID')),
                ('error_message', models.TextField(blank=True, help_text='处理失败时的错误信息', null=True, verbose_name='错误信息')),
                ('audio_duration', models.IntegerField(default=0, help_text='累计录音时长（秒，不包括暂停时间）', verbose_name='录音时长')),
                ('audio_size', models.BigIntegerField(default=0, help_text='临时音频文件大小（字节）', verbose_name='音频大小')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('meeting', models.OneToOneField(help_text='关联会议（一个会议同时只能有一个实时录音会话）', on_delete=django.db.models.deletion.CASCADE, related_name='realtime_session', to='meet.meeting', verbose_name='关联会议')),
                ('recording', models.ForeignKey(blank=True, help_text='处理完成后生成的Recording记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_session', to='meet.recording', verbose_name='关联录音')),
            ],
            options={
                'verbose_name': '实时录音会话',
                'verbose_name_plural': '实时录音会话',
                'db_table': 'meet_realtime_recording_session',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['session_id'], name='meet_realti_session_c820fe_idx'), models.Index(fields=['meeting', 'recording_status'], name='meet_realti_meeting_9d5760_idx')],
            },
        ),
    ]
