# Generated by Django 5.2.5 on 2025-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_users_post_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='column',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='列表权限', null=True, to='system.menucolumnfield', verbose_name='列表权限'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='关联菜单', null=True, to='system.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='关联菜单的接口按钮', null=True, to='system.menubutton', verbose_name='关联菜单的接口按钮'),
        ),
        migrations.AlterField(
            model_name='users',
            name='home_path',
            field=models.CharField(blank=True, default='', help_text='首页路径', max_length=150, null=True, verbose_name='首页路径'),
        ),
    ]
