# Generated by Django 5.2.5 on 2025-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_role_column_alter_role_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(help_text='url', upload_to='files/', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, '后台用户'), (1, '前台用户')], default=1, help_text='用户类型', null=True, verbose_name='用户类型'),
        ),
    ]
