# Generated by Django 5.2.5 on 2025-09-16 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20250916_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='文件唯一标识符', null=True, unique=True, verbose_name='文件UUID'),
        ),
    ]
